apiVersion: apps/v1
kind: Deployment
metadata:
  name: log
spec:
  selector:
    matchLabels:
      app: log
  replicas: 1
  template:
    metadata:
      labels:
        app: log
    spec:
      containers:
        - name: log-service
          image: 01720588884/log-service:8.0.0
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 200m
            requests:
              cpu: 100m

---
apiVersion: v1
kind: Service
metadata:
  name: log-svc
  labels:
    app: log
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3001
  selector:
    app: log
